---
name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  Credo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          hex-token: ${{ secrets.HEX_API_KEY }}

      - name: Credo
        run: mix credo

  Dialyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          hex-token: ${{ secrets.HEX_API_KEY }}

      - name: Dialyzer
        run: mix dialyzer

  Doctor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          hex-token: ${{ secrets.HEX_API_KEY }}

      - name: Doctor
        run: mix doctor

  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          hex-token: ${{ secrets.HEX_API_KEY }}

      - name: Format
        run: mix format --check-formatted

  Test:
    name: Test (Elixir ${{ matrix.versions.elixir }} OTP ${{ matrix.versions.otp }})
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        versions:
          - elixir: 1.11
            otp: 23
          - elixir: 1.12
            otp: 24
          - elixir: 1.13
            otp: 25
          - elixir: 1.14
            otp: 25
          - elixir: 1.15
            otp: 25

    env:
      MIX_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          elixir-version: ${{ matrix.versions.elixir }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          hex-token: ${{ secrets.HEX_API_KEY }}
          otp-version: ${{ matrix.versions.otp }}

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Test
        run: mix test --cover
