---
name: Release

on:
  push:
    branches:
      - main

jobs:
  please:
    name: Please
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: elixir
          package-name: dd_data_streams
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          extra-files: README.md
