# This file is synced with stordco/common-config-elixir. Any changes will be overwritten.

name: Staging

on:
  push:
    branches:
      - main
      - code-freeze/**
  workflow_dispatch:

concurrency:
  group: Staging

jobs:
  Documentation:
    environment:
      name: Documentation
      url: https://data-streams-ex.stord.engineering

    permissions:
      actions: read
      contents: read
      id-token: write
      pages: write

    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          hex-token: ${{ secrets.HEX_API_KEY }}
          oban-fingerprint: ${{ secrets.OBAN_KEY_FINGERPRINT }}
          oban-token: ${{ secrets.OBAN_LICENSE_KEY }}

      - name: Docs
        run: mix docs

      - name: Set CNAME
        run: echo "data-streams-ex.stord.engineering" > ./doc/CNAME

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./doc

      - name: Deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

